---
key_out: /etc/pki/tls/private/portal.example.org.key
cert_out: /etc/pki/tls/certs/portal.example.org.crt
key_type: "rsa:2048"

country_name: NL
state_or_province_name: Noord-Holland
locality_name: Amsterdam
organisation: Example BV
organisational_unit: IT
email_unit: it
default_bits: 2048
